CREATE TABLE products(
  ID                  BIGINT(20) PRIMARY KEY  NOT NULL AUTO_INCREMENT,
  CREATED_AT          TIMESTAMP               NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT          TIMESTAMP               NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  MSG_SEQ_NR          BIGINT(20)              NOT NULL,
  ACTIVATION_TIME     TIMESTAMP               NOT NULL,
  CATEGORY_L1         TEXT                    NOT NULL,
  CATEGORY_L2         TEXT,
  CATEGORY_L3         TEXT,
  CURRENCY            TEXT                    NOT NULL,
  DESCRIPTION         TEXT                    NOT NULL,
  DISCOUNT_AMOUNT     DECIMAL,
  EXPIRATION_TIME     TIMESTAMP               NOT NULL,
  GROSS_PRICE         DECIMAL                 NOT NULL,
  NAME                TEXT                    NOT NULL,
  NET_PRICE           DECIMAL,
  ORDER_ITEM_ID       TEXT                    NOT NULL,
  PACKAGE_ID          TEXT                    NOT NULL,
  REVENUE_CLASS       TEXT                    NOT NULL,
  SKU_ID              TEXT                    NOT NULL,
  TYPE                TEXT                    NOT NULL,
  UNIT_PRICE          DECIMAL                 NOT NULL,
  UNITS               BIGINT(20)              NOT NULL
)